name: wbs-dev

networks:
  default:
    name: wbs-dev
    external: true

services:
  runner:
    image: wbs-dev-runner:latest
    scale: 0
    build:
      context: .
    stop_grace_period: 1s
    ports:
      - 9229:9229
      - 4211:4211
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - test/test-runner.env
      - local.env
    environment:
      HOST_PWD: $PWD

# We need this somewhat unexpected/hacky but functional thing to be able to use "runner" with the
# repo volume mapped into the container (vs copied in each run) as node_modules must exist within
# the root of the repository. For more details on how this works see:
# https://stackoverflow.com/a/67010277
#
# NOTE: One possible less hacky solution may be to copy the `package-lock.json` files and workspace
# subdirs into another directory in the container and then set that in the path in the container.
# According to this StackOverflow answer that may work fine with careful design:
# https://stackoverflow.com/a/26293141
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
