name: wbs-dev

networks:
  default:
    name: wbs-dev

services:
  runner:
    image: ghcr.io/wmde/wbs-dev-runner:latest
    scale: 0
    build:
      context: .
      tags:
        - ghcr.io/wmde/wbs-dev-runner:latest
    stop_grace_period: 1s
    ports:
      - 9229:9229
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOST_PWD: ${PWD}/test

# https://stackoverflow.com/a/67010277
volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
