services:
  wikibase:
    image: ${WIKIBASE_SUITE_WIKIBASE_IMAGE_URL?}:${WBS_WIKIBASE_VERSION?}
    build:
      context: ./build/Wikibase
      args:
        - PHP_IMAGE_URL
        - COMPOSER_IMAGE_URL
        - MEDIAWIKI_VERSION
        - WIKIBASE_COMMIT
        - BABEL_COMMIT
        - CLDR_COMMIT
        - CIRRUSSEARCH_COMMIT
        - CONFIRMEDIT_COMMIT
        - ELASTICA_COMMIT
        - ENTITYSCHEMA_COMMIT
        - NUKE_COMMIT
        - OAUTH_COMMIT
        - SCRIBUNTO_COMMIT
        - SYNTAXHIGHLIGHT_GESHI_COMMIT
        - UNIVERSALLANGUAGESELECTOR_COMMIT
        - VISUALEDITOR_COMMIT
        - WIKIBASECIRRUSSEARCH_COMMIT
        - WIKIBASEMANIFEST_COMMIT
        - WIKIBASEEDTF_COMMIT
        - WIKIBASELOCALMEDIA_COMMIT
      tags:
        - ${WIKIBASE_SUITE_WIKIBASE_IMAGE_URL?}:${WBS_WIKIBASE_VERSION_MAJOR?}
        - ${WIKIBASE_SUITE_WIKIBASE_IMAGE_URL?}:${WBS_WIKIBASE_VERSION_MINOR?}
        - ${WIKIBASE_SUITE_WIKIBASE_IMAGE_URL?}:mw${MEDIAWIKI_VERSION?}

  elasticsearch:
    image: ${WIKIBASE_SUITE_ELASTICSEARCH_IMAGE_URL?}:${WBS_ELASTICSEARCH_VERSION?}
    build:
      context: ./build/Elasticsearch
      args:
        - ELASTICSEARCH_IMAGE_URL
        - ELASTICSEARCH_PLUGIN_WIKIMEDIA_EXTRA
        - ELASTICSEARCH_PLUGIN_WIKIMEDIA_HIGHLIGHTER
      tags:
        - ${WIKIBASE_SUITE_ELASTICSEARCH_IMAGE_URL?}:${WBS_ELASTICSEARCH_VERSION_MAJOR?}
        - ${WIKIBASE_SUITE_ELASTICSEARCH_IMAGE_URL?}:${WBS_ELASTICSEARCH_VERSION_MINOR?}
        - ${WIKIBASE_SUITE_ELASTICSEARCH_IMAGE_URL?}:es${ELASTICSEARCH_VERSION?}

  wdqs:
    image: ${WIKIBASE_SUITE_WDQS_IMAGE_URL?}:${WBS_WDQS_VERSION?}
    build:
      context: ./build/WDQS
      args:
        - DEBIAN_IMAGE_URL
        - JRE_IMAGE_URL
        - WDQS_VERSION
      tags:
        - ${WIKIBASE_SUITE_WDQS_IMAGE_URL?}:${WBS_WDQS_VERSION_MAJOR?}
        - ${WIKIBASE_SUITE_WDQS_IMAGE_URL?}:${WBS_WDQS_VERSION_MINOR?}
        - ${WIKIBASE_SUITE_WDQS_IMAGE_URL?}:wdqs${WDQS_VERSION?}

  wdqs-frontend:
    image: ${WIKIBASE_SUITE_WDQS_FRONTEND_IMAGE_URL?}:${WBS_WDQS_FRONTED_VERSION?}
    build:
      context: ./build/WDQS-frontend
      args:
        - COMPOSER_IMAGE_URL
        - NGINX_IMAGE_URL
        - NODE_IMAGE_URL
        - WDQSQUERYGUI_COMMIT
      tags:
        - ${WIKIBASE_SUITE_WDQS_FRONTEND_IMAGE_URL?}:${WBS_WDQS_FRONTED_VERSION_MAJOR?}
        - ${WIKIBASE_SUITE_WDQS_FRONTEND_IMAGE_URL?}:${WBS_WDQS_FRONTED_VERSION_MINOR?}

  wdqs-proxy:
    image: ${WIKIBASE_SUITE_WDQS_PROXY_IMAGE_URL?}:${WBS_WDQS_PROXY_VERSION?}
    build:
      context: ./build/WDQS-proxy
      args:
        - NGINX_IMAGE_URL
      tags:
        - ${WIKIBASE_SUITE_WDQS_PROXY_IMAGE_URL?}:${WBS_WDQS_PROXY_VERSION_MAJOR?}
        - ${WIKIBASE_SUITE_WDQS_PROXY_IMAGE_URL?}:${WBS_WDQS_PROXY_VERSION_MINOR?}

  quickstatements:
    image: ${WIKIBASE_SUITE_QUICKSTATEMENTS_IMAGE_URL?}:${WBS_QUICKSTATEMENTS_VERSION?}
    build:
      context: ./build/QuickStatements
      args:
        - COMPOSER_IMAGE_URL
        - PHP_IMAGE_URL
        - QUICKSTATEMENTS_COMMIT
        - MAGNUSTOOLS_COMMIT
      tags:
        - ${WIKIBASE_SUITE_QUICKSTATEMENTS_IMAGE_URL?}:${WBS_QUICKSTATEMENTS_VERSION_MAJOR?}
        - ${WIKIBASE_SUITE_QUICKSTATEMENTS_IMAGE_URL?}:${WBS_QUICKSTATEMENTS_VERSION_MINOR?}
        - ${WIKIBASE_SUITE_QUICKSTATEMENTS_IMAGE_URL?}:qs${QUICKSTATEMENTS_VERSION?}
