on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - run: pnpm exec nx lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        component:
          - wikibase
          - elasticsearch
          - wdqs
          - wdqs-frontend
          - wdqs-proxy
          - quickstatements

    steps:
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Building ${{ matrix.component }}
        run: |
          export PR_BUILD_TAG=ghcr.io/${{ github.repository_owner }}/wikibase/${{ matrix.component }}:dev-${{ github.run_id }}
          pnpm exec nx build ${{ matrix.component }} --set default.tags=$PR_BUILD_TAG --push

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        suite:
          - repo
          - fedprops
          - repo_client
          - quickstatements
          - pingback
          - confirm_edit
          - elasticsearch
          - deploy

    steps:
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pnpm install

      - uses: ./.github/actions/pull-ghcr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm exec nx build -- ${{ matrix.suite }}

      - name: Show logs
        run: |
          ls -lahr test/suites/${{ matrix.suite }}/results test/suites/${{ matrix.suite }}/results/*
          tail -n +1 test/suites/${{ matrix.suite }}/results/*.log
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: test/suites/**/results

  test-success:
    # Post-test CI step - to check all tests succeeded
    # Github Branch Protection rules require this to pass to allow merging
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - run: true
